server:
  # debug -4
  # info   0
  # warn   4 
  # error  8
  log_level: 0

  # true|false
  log_json: false

  # host:port
  address: 127.0.0.1:8080

  # in ms
  shutdown_timeout: 2000

  # in ms
  connection_timeout: 30000

  # in ms
  puzzle_clear_interval: 2000

hashcash:
  # number of zero bits in hashed code
  bits: 5

  # in ms
  ttl: 60000