client:
  # debug -4
  # info   0
  # warn   4 
  # error  8
  log_level: 0

  # true|false
  log_json: false

  # host:port
  server_address: 127.0.0.1:8080

hashcash:
  # max attempts to compute hashcash
  compute_max_attempts: 100000000